server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password:taulogy1!
    url: jdbc:postgresql://localhost:5432/LoginDB
    username:postgres
  joa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect
        format_sql: true
    show-sql: true

